### ISSUE TITLE
Can't download the files from dropbox

### ISSUE THREAD

**Issue by PandaPYH** [yashkant/concat-vqa#1]
Hi, I want to download the data to run the model.
However, I can't download the files from dropbox. (the website https://www.dropbox.com/sh/v826l3ge7oz4vz4/AACRimDdy_BGnN2XZJDZLyY6a?dl=0)

**Comment by jiyt17** [comment]
I can't open it, too. The webpage has a mistake.

**Comment by yashkant** [comment]
Hi, I have fixed the link. Please let me know if the issue still persists.
