### ISSUE TITLE
Corresponding images

### ISSUE THREAD

**Issue by JurijsNazarovs** [yashkant/concat-vqa#10]
Hello,

Thanks for the code and provided extracted features for images. However, I would like to see corresponding images, where should I get them? I see that data contains information about image id, however, I am not sure where are these images.

Thanks,
Jurijs

**Comment by yashkant** [comment]
The images come from VQA dataset.

**Comment by yashkant** [comment]
Which is built on top of COCO — https://visualqa.org/download.html

**Comment by JurijsNazarovs** [comment]
Thank you!

**Comment by JurijsNazarovs** [comment]
@yashkant  by the way, do you know if there is a way to get annotation for derived boxes/features of images? As I understand, you used Fast RCNN to get 100 boxes per image. Can we somehow get what these boxes are, e.g. cat, dog, banana and so on? Please, correct me if my understanding is wrong.
