### ISSUE TITLE
Extracting features Install vqa-maskrcnn-benchmark(link) repository and download the model and config.

### ISSUE THREAD

**Issue by alice-cool** [yashkant/concat-vqa#3]
Dear scholar,
I found the link vqa-maskrcnn-benchmark didn't have the folder named as "data-release",where I can download it? So I can't run the instructions about the below procedures

cd data-release
wget https://dl.fbaipublicfiles.com/vilbert-multi-task/detectron_model.pth
wget https://dl.fbaipublicfiles.com/vilbert-multi-task/detectron_config.yaml
To extract features for images, run from root directory:

python data-release/extract_features.py --model_file data/detectron_model.pth --config_file data/detectron_config.yaml --image_dir <pa

**Comment by ApoorvVerma5** [comment]
Have you got the solution to this?
